# Generated by Django 5.0.7 on 2024-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_leccion_ejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='curso',
            name='explicacion',
            field=models.TextField(default='vacio'),
            preserve_default=False,
        ),
    ]
