# Generated by Django 5.0.7 on 2024-07-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_curso_subtitulo_curso_explicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
    ]
