# Generated by Django 5.0.7 on 2024-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='imagen',
            field=models.ImageField(default='vacio', upload_to='images/'),
            preserve_default=False,
        ),
    ]
