# Generated by Django 5.0.7 on 2024-07-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_leccion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen1',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen2',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen3',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen4',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen5',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
    ]
