# Generated by Django 5.0.7 on 2024-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_imagen1_curso_imagen2_curso_imagen3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen5',
        ),
        migrations.AddField(
            model_name='leccion',
            name='imagen1',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='imagen2',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='imagen3',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='imagen4',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='imagen5',
            field=models.ImageField(default='nada', upload_to='images/'),
            preserve_default=False,
        ),
    ]
