# Generated by Django 5.0.7 on 2024-07-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_curso_imagen1_remove_curso_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='curso',
            name='miniatura',
            field=models.ImageField(default='nada', upload_to='images/miniaturas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='miniatura',
            field=models.ImageField(default='nada', upload_to='images/miniaturas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen1',
            field=models.ImageField(upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen2',
            field=models.ImageField(upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen3',
            field=models.ImageField(upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen4',
            field=models.ImageField(upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen5',
            field=models.ImageField(upload_to='images/lecciones/'),
        ),
    ]
