# Generated by Django 5.0.7 on 2024-08-03 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_curso_imagen_remove_leccion_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_completaron', to='cursos.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_completadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
