# Generated by Django 5.0.7 on 2024-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_usuarioleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='miniexplicacion',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
