# Generated by Django 5.0.7 on 2024-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_curso_miniexplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='explicacion',
            field=models.TextField(default='Resumen del contenido de la lección'),
            preserve_default=False,
        ),
    ]
