# Generated by Django 5.0.7 on 2024-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_leccion_explicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecciones/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecciones/'),
        ),
    ]
