# Generated by Django 5.0.7 on 2024-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_leccion_imagen1_alter_leccion_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.PositiveIntegerField(default='10'),
            preserve_default=False,
        ),
    ]
