# Generated by Django 5.0.7 on 2024-08-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_curso_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/lecciones/')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cursos.leccion')),
            ],
        ),
    ]
