# Generated by Django 5.0.7 on 2024-08-12 15:34

from django.db import migrations, models
import os

def transfer_images(apps, schema_editor):
    Leccion = apps.get_model('cursos', 'Leccion')
    ImagenLeccion = apps.get_model('cursos', 'ImagenLeccion')

    for leccion in Leccion.objects.all():
        # Transferir cada imagen al nuevo modelo
        for i in range(1, 6):
            imagen = getattr(leccion, f'imagen{i}')
            if imagen:
                ImagenLeccion.objects.create(leccion=leccion, imagen=imagen)


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_imagenleccion'),
    ]

    operations = [
        migrations.RunPython(transfer_images),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='imagen5',
        ),
    ]
