# Generated by Django 5.0.7 on 2024-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_remove_leccion_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='explicacion',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
