# Generated by Django 5.0.7 on 2024-08-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_usuarioleccion_puntos_obtenidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.CharField(max_length=255)),
                ('opciones', models.CharField(max_length=255)),
                ('respuestas', models.CharField(max_length=255)),
            ],
        ),
    ]
