# Generated by Django 5.0.7 on 2024-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_cuestionario_pregunta_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='importancia',
            field=models.PositiveIntegerField(choices=[(1, 'Poco importante'), (2, 'Interesante'), (3, 'Fundamental')], default=2),
            preserve_default=False,
        ),
    ]
