# Generated by Django 5.0.7 on 2024-09-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.categoria'),
            preserve_default=False,
        ),
    ]
